Repository Notiooo/PawTravel, pull requests merged in 2022-05, with the labels that each got.

#72 Add proper URL pattern for serving static files
  PawTravel/PawTravel/settings.py
  PawTravel/PawTravel/urls.py
  PawTravel/static/.gitkeep
Labels: bug

#73 Add backend and models for the offer detail page - #52
  PawTravel/PawTravel/settings.py
  PawTravel/PawTravel/urls.py
  PawTravel/offers/__init__.py
  PawTravel/offers/admin.py
  PawTravel/offers/apps.py
  PawTravel/offers/models.py
  PawTravel/offers/templates/detailed_offer.html
  PawTravel/offers/tests.py
  PawTravel/offers/urls.py
  PawTravel/offers/views.py
  PawTravel/uploads/avatars/default.png
  PawTravel/users/migrations/0001_initial.py
  PawTravel/users/models.py
  pawTravelEnv/requirements.txt
Labels: backend

#71 Add web design of detailed display of the offer - #41
  PawTravel/offers/templates/detailed_offer.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
Labels: frontend

#77 Change the naming to pep 8 and move the frontend to Vue folder
  PawTravel/PawTravel/settings.py
  PawTravel/offers/models.py
  PawTravel/offers/tests.py
  PawTravel/offers/views.py
  PawTravel/pawtravel-front/public/templates/offers/detailed_offer.html
  PawTravel/users/forms.py
  PawTravel/users/models.py
Labels: bug, frontend, backend

#76 Users system (including login/registration)
  PawTravel/PawTravel/settings.py
  PawTravel/PawTravel/urls.py
  PawTravel/pawtravel-front/public/templates/avatar/add.html
  PawTravel/pawtravel-front/public/templates/avatar/base.html
  PawTravel/pawtravel-front/public/templates/avatar/change.html
  PawTravel/pawtravel-front/public/templates/avatar/confirm_delete.html
  PawTravel/pawtravel-front/public/templates/registration/login.html
  PawTravel/pawtravel-front/public/templates/registration/password_change_done.html
  PawTravel/pawtravel-front/public/templates/registration/password_change_form.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_complete.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_confirm.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_done.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_email.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_form.html
  PawTravel/pawtravel-front/public/templates/registration/password_reset_subject
  PawTravel/pawtravel-front/public/templates/users/signup.html
  PawTravel/static/css/pawtravel.css
  PawTravel/static/css/uikit-rtl.css
  PawTravel/static/css/uikit-rtl.min.css
  PawTravel/static/css/uikit.min.css
  PawTravel/static/img/favicon.ico
  PawTravel/static/js/uikit-icons.js
  PawTravel/static/js/uikit-icons.min.js
  PawTravel/static/js/uikit.min.js
  PawTravel/templates/base.html
  PawTravel/templates/base/.gitkeep
  PawTravel/templates/base/footer.html
  PawTravel/templates/base/navbar.html
  PawTravel/templates/favicon.ico
  PawTravel/users/admin.py
  PawTravel/users/authentication.py
  PawTravel/users/forms.py
  PawTravel/users/models.py
  PawTravel/users/serializers.py
  PawTravel/users/tests.py
  PawTravel/users/urls.py
  PawTravel/users/views.py
  pawTravelEnv/requirements.txt
  pawTravelEnv/socialAuthKeySetter.bat
Labels: backend

#78 Add web design of login and registration panel
  PawTravel/pawtravel-front/public/templates/base.html
  PawTravel/pawtravel-front/public/templates/base/navbar.html
  PawTravel/pawtravel-front/public/templates/offers/detailed_offer.html
  PawTravel/pawtravel-front/public/templates/registration/login.html
  PawTravel/pawtravel-front/public/templates/users/register.html
  PawTravel/pawtravel-front/public/templates/users/signup.html
  PawTravel/pawtravel-front/static/css/blobz.min.css
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/pawtravel-front/static/img/login/cat.png
  PawTravel/pawtravel-front/static/img/login/facebook.png
  PawTravel/pawtravel-front/static/img/login/google.png
  PawTravel/pawtravel-front/static/img/login/linkedin.png
  PawTravel/users/urls.py
  PawTravel/users/views.py
Labels: frontend

#79 Dev/issue61 Travel guides
  .gitignore
  PawTravel/PawTravel/settings.py
  PawTravel/PawTravel/urls.py
  PawTravel/pawtravel-front/public/templates/base.html
  PawTravel/pawtravel-front/public/templates/travel_guides/form.html
  PawTravel/pawtravel-front/public/templates/travel_guides/guide_detail.html
  PawTravel/pawtravel-front/public/templates/travel_guides/guide_list.html
  PawTravel/pawtravel-front/public/templates/travel_guides/pagination.html
  PawTravel/travel_guides/__init__.py
  PawTravel/travel_guides/admin.py
  PawTravel/travel_guides/apps.py
  PawTravel/travel_guides/forms.py
  PawTravel/travel_guides/models.py
  PawTravel/travel_guides/tests.py
  PawTravel/travel_guides/urls.py
  PawTravel/travel_guides/views.py
Labels: backend

#80 Add web design and backend for desktop and mobile navbar
  PawTravel/PawTravel/settings.py
  PawTravel/pawtravel-front/public/templates/base.html
  PawTravel/pawtravel-front/public/templates/base/navbar.html
  PawTravel/pawtravel-front/public/templates/registration/login.html
  PawTravel/pawtravel-front/public/templates/users/register.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/pawtravel-front/static/img/pawtravel.png
  pawTravelEnv/requirements.txt
Labels: frontend, backend
