Repository Notiooo/PawTravel, pull requests merged in 2022-09, with the labels that each got.

#97 Add frontend for voting system
  PawTravel/pawtravel-front/public/templates/offers/detailed_offer.html
  PawTravel/pawtravel-front/public/templates/travel_guides/guide_detail.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/pawtravel-front/static/img/voting/down-paw.png
  PawTravel/pawtravel-front/static/img/voting/up-paw.png
  PawTravel/pawtravel-front/static/js/like_system.js
Labels: frontend

#99 Web design of the user profile - #43
  PawTravel/pawtravel-front/public/templates/users/profile.html
  PawTravel/pawtravel-front/public/templates/users/user_profile_activities.html
  PawTravel/pawtravel-front/public/templates/users/user_profile_added.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/pawtravel-front/static/img/placeholders/avatars/avataro.jpg
  PawTravel/pawtravel-front/static/img/placeholders/badges/trusted.png
  PawTravel/users/models.py
  PawTravel/users/urls.py
  PawTravel/users/views.py
Labels: frontend

#98 Message system #56
  .gitignore
  PawTravel/PawTravel/settings.py
  PawTravel/PawTravel/urls.py
  PawTravel/chat/__init__.py
  PawTravel/chat/admin.py
  PawTravel/chat/apps.py
  PawTravel/chat/models.py
  PawTravel/chat/tests.py
  PawTravel/chat/urls.py
  PawTravel/chat/views.py
Labels: functionality, backend

#101 Add a very basic imitation of a homepage - #100
  PawTravel/PawTravel/urls.py
  PawTravel/offers/models.py
  PawTravel/offers/views.py
  PawTravel/pawtravel-front/public/templates/base/navbar.html
  PawTravel/pawtravel-front/public/templates/offers/homepage_offers.html
  PawTravel/pawtravel-front/public/templates/travel_guides/homepage_travel_guides.html
  PawTravel/pawtravel-front/public/templates/users/user_profile.html
  PawTravel/pawtravel-front/public/templates/users/user_profile_activities.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/pawtravel-front/static/img/placeholders/placeholder_homepage.jpg
  PawTravel/travel_guides/models.py
  PawTravel/travel_guides/urls.py
  PawTravel/travel_guides/views.py
  PawTravel/users/urls.py
  PawTravel/users/views.py
Labels: frontend, backend

#102 Add web design of user settings - #46
  PawTravel/pawtravel-front/public/templates/users/edit_profile.html
  PawTravel/pawtravel-front/public/templates/users/manage_profile.html
  PawTravel/pawtravel-front/public/templates/users/profile.html
  PawTravel/pawtravel-front/static/css/pawtravel.css
  PawTravel/users/urls.py
  PawTravel/users/views.py
Labels: frontend

#104 Add correct links between pages and minor corrections
  PawTravel/PawTravel/settings.py
  PawTravel/pawtravel-front/public/templates/base/navbar.html
  PawTravel/pawtravel-front/public/templates/travel_guides/create_form.html
  PawTravel/pawtravel-front/public/templates/users/edit_profile.html
  PawTravel/pawtravel-front/public/templates/users/manage_profile.html
  PawTravel/pawtravel-front/public/templates/users/profile.html
  PawTravel/pawtravel-front/public/templates/users/user_profile.html
  PawTravel/pawtravel-front/public/templates/users/user_profile_activities.html
  PawTravel/travel_guides/tests.py
  PawTravel/travel_guides/urls.py
  PawTravel/travel_guides/views.py
  PawTravel/users/urls.py
  PawTravel/users/views.py
Labels: bug, frontend, backend
